// <auto-generated />
using System;
using HomeWork.Infrastructur;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HomeWork.Infrastructure.Migrations
{
    [DbContext(typeof(HomeWorkDbContext))]
    partial class HomeWorkDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HomeWork.Models.Laptop", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("LastModified")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RAMSizeGB")
                        .HasColumnType("int");

                    b.Property<string>("ScreenSizeInches")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Laptops", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Color = "Black",
                            Created = new DateTimeOffset(new DateTime(2023, 7, 17, 14, 3, 42, 884, DateTimeKind.Unspecified).AddTicks(171), new TimeSpan(0, 6, 0, 0, 0)),
                            CreatedBy = "1",
                            Model = "Walton",
                            RAMSizeGB = 64,
                            ScreenSizeInches = "6 inhci",
                            Status = 1
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
